#!/bin/bash

source $DIR/functions/non-apt/instvim
source $DIR/functions/non-apt/instpandoc
source $DIR/functions/non-apt/instpython
source $DIR/functions/non-apt/sourcecodepro
source $DIR/functions/non-apt/travis
source $DIR/functions/non-apt/rpackages

# Install packages listed in 'data/packages.list'
function doall {
    whiptail --title "NOTE"  --msgbox "Prior to running doall, software-properties-common may need to be reinstalled - check first!" 8 78
    show_info "check with $ apt install software-properties-common"
    if (eval `resize` && whiptail \
        --title "Everything" \
        --yesno "Install and setup whole system non-interactively?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then

        # ---repeated  -nv to update  timestamp
         -nv

        # ---aptadd
        addkeys
        addrepos

        # ---packages
         -nv
        while read F ; do
            PF=$(echo $F | cut -d "#" -f 1) # cut comments from package names
            PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PF|grep "install ok installed")
            if [ "" == "$PKGCHECK" ]
            then
                 apt install -y $PF
            else
                echo "package "$PF" already installed"
            fi
        done < $PKGS
         R CMD javareconf
        gdal

        # ---nonapt
         -nv
        set_preferences
        dotfiles

        # ---non-apt/instvim
         -nv
        install_vim_core
        pathogen
        solarized
        # ---non-apt/pandoc
         -nv
        install_pandoc_core
        # ---non-apt/sourcecodepro
         -nv
        install_sourcecodepro
        # ---non-apt/travis
         -nv
         apt install -y ruby-dev
         gem install travis --no-rdoc --no-ri
        # ---non-apt/rpackages
         -nv
        if [ -d "$RLIBLOC" ]; then
            while read F ; do
                CMD='install.packages('\"$F\"',repos='\"$CRAN\"',lib.loc='\"$RLIBLOC\"')'
                echo  Rscript --verbose -e $CMD
            done < $RPKGS
        else
            while read F ; do
                CMD='install.packages('\"$F\"',repos='\"$CRAN\"')'
                 Rscript --verbose -e $CMD
            done < $RPKGS
        fi
        # ---non-apt/python
         -nv
        install_python

        # Done
        show_success 'Done.'
        main
    else
        main
    fi
}
