#!/bin/bash

# Install packages listed in 'data/packages.list'
function packages {

    show_info 'Installing...'
    show_warning 'Requires root privileges'
    while read F ; do
        sudo pacman -S --noconfirm "$F"
    done < $PKGS

    show_success 'Done.'

    whiptail --title "Finished" --msgbox "All packages installed." 8 78
    main
}
